FROM python:3.9
COPY . /app
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
COPY Scores.txt /Scores.txt
ENV FLASK_APP=MainScores.py
EXPOSE 5000
CMD ["python",MainScores.py"]
