version: '3'

services:
  flask-app:
    build: .
    ports:
      - 8777:5000
    volumes:
      - ./Scores.txt:/Scores.txt
    command: python MainScores.py
    image: maoravidan/flask-app:latest
